import { h, picker, statusBar, isPdf, openPdfjs, openPdfLib, pageViewer, getPdfLib, pdfBlob, stem } from "./common.js";
import { embedUnicodeFont } from "../pdfwriter.js";
import { downloadBlob, formatBytes } from "../util.js";

// With "auto" (0) font size, pdf-lib grows text to fill the box — up to 60pt in a
// multi-line field, which clips everything after the first word. Forms generated by
// pdf-lib often have such a size baked in. Replace unusable sizes with a normal one.
function fixAutoFontSize(field, multiline) {
  const m = (field.acroField.getDefaultAppearance() || "").match(/([\d.]+)\s+Tf/);
  const size = m ? +m[1] : 0;
  const hgt = field.acroField.getWidgets()[0]?.getRectangle().height || 20;
  const unusable = size === 0 || (multiline ? size * 2.4 > hgt : size > hgt);
  if (!unusable) return;
  try {
    field.setFontSize(multiline ? Math.min(11, Math.max(6, hgt / 4)) : Math.min(12, Math.max(6, hgt * 0.62)));
  } catch {}
}

export default {
  id: "forms",
  title: "Fill forms",
  desc: "Fill in a PDF's form fields and save it, optionally locked.",
  icon: '<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M7 9l1.5 1.5L11 8M7 15.5l1.5 1.5L11 14.5M14 9.5h3M14 16h3"/>',
  mount(root) {
    let state = null;
    const status = statusBar();
    const viewer = h("div", { class: "viewer" });
    const info = h("p", { class: "tool-file", hidden: true });
    const empty = h("div", { class: "empty-note", hidden: true });
    const flatten = h("input", { type: "checkbox" });
    const opts = h("label", { class: "check", hidden: true }, flatten, "Lock the form after filling (flatten)");
    const go = h("button", { class: "btn primary", disabled: true, onclick: save }, "Save filled PDF");
    const pick = picker({ multiple: false, label: "Choose a PDF form", onFiles: addFiles });
    root.append(pick.el, info, empty, viewer, h("div", { class: "tool-actions sticky" }, status.el, opts, go));

    async function addFiles(files) {
      const file = files.find(isPdf);
      if (!file) return status.set("Please choose a PDF file.", "error");
      viewer.replaceChildren();
      state = null;
      go.disabled = true;
      empty.hidden = opts.hidden = true;
      status.set("Opening…");
      try {
        const PDFLib = await getPdfLib();
        const bytes = new Uint8Array(await file.arrayBuffer());
        const doc = await openPdfLib(bytes);
        const fields = doc.getForm().getFields().filter((f) => !(f instanceof PDFLib.PDFButton || f instanceof PDFLib.PDFSignature));
        info.textContent = `${file.name} · ${doc.getPageCount()} page${doc.getPageCount() === 1 ? "" : "s"} · ${fields.length} field${fields.length === 1 ? "" : "s"} · ${formatBytes(file.size)}`;
        info.hidden = false;
        if (!fields.length) {
          status.set("");
          empty.replaceChildren(
            h("p", {}, "This PDF has no fillable form fields."),
            h("button", { class: "btn primary", onclick: () => root.dispatchEvent(new CustomEvent("open-tool", { bubbles: true, detail: { tool: "sign", files: [file] } })) }, "Type on it with Sign & add text instead"));
          empty.hidden = false;
          return;
        }
        const { pdf, close } = await openPdfjs(bytes);
        let pages;
        try {
          pages = await pageViewer(viewer, pdf, { forms: false });
        } finally {
          close();
        }
        state = { bytes, name: file.name, controls: buildControls(PDFLib, doc, fields, pages) };
        opts.hidden = false;
        go.disabled = false;
        status.set(`${fields.length} field${fields.length === 1 ? "" : "s"} ready to fill`);
      } catch (e) {
        status.fail(e);
      }
    }

    function buildControls(PDFLib, doc, fields, pages) {
      const pageOf = new Map();
      doc.getPages().forEach((p, i) => {
        for (const ref of p.node.Annots()?.asArray() || []) pageOf.set(doc.context.lookup(ref), i);
      });
      const controls = [];
      for (const field of fields) {
        const widgets = field.acroField.getWidgets();
        const readOnly = field.isReadOnly();
        const c = { field, inputs: [] };
        if (field instanceof PDFLib.PDFTextField) c.type = "text";
        else if (field instanceof PDFLib.PDFCheckBox) c.type = "check";
        else if (field instanceof PDFLib.PDFRadioGroup) c.type = "radio";
        else if (field instanceof PDFLib.PDFDropdown) c.type = "select";
        else if (field instanceof PDFLib.PDFOptionList) c.type = "list";
        else continue;
        const radioOpts = c.type === "radio" ? field.getOptions() : null;
        widgets.forEach((w, wi) => {
          const pi = pageOf.get(w.dict);
          if (pi == null || !pages[pi]) return;
          const page = pages[pi];
          const r = w.getRectangle();
          const [x1, y1] = page.viewport.convertToViewportPoint(r.x, r.y);
          const [x2, y2] = page.viewport.convertToViewportPoint(r.x + r.width, r.y + r.height);
          const box = { left: Math.min(x1, x2), top: Math.min(y1, y2), width: Math.abs(x2 - x1), height: Math.abs(y2 - y1) };
          const label = field.getName();
          let input;
          if (c.type === "text") {
            const multi = field.isMultiline();
            input = h(multi ? "textarea" : "input", { class: "ff", "aria-label": label, title: label });
            input.value = field.getText() ?? "";
            const max = field.getMaxLength();
            if (max) input.maxLength = max;
            input.style.fontSize = `${Math.max(9, Math.min(multi ? 13 : box.height * 0.62, 16))}px`;
          } else if (c.type === "check") {
            input = h("input", { type: "checkbox", class: "ff ff-check", "aria-label": label, title: label });
            input.checked = field.isChecked();
          } else if (c.type === "radio") {
            input = h("input", { type: "radio", class: "ff ff-check", name: `rg-${label}`, value: radioOpts[wi], "aria-label": `${label}: ${radioOpts[wi]}`, title: `${label}: ${radioOpts[wi]}` });
            input.checked = field.getSelected() === radioOpts[wi];
          } else {
            input = h("select", { class: "ff", "aria-label": label, title: label, multiple: c.type === "list" });
            const selected = new Set(field.getSelected());
            if (c.type === "select") input.append(new Option("", ""));
            for (const o of field.getOptions()) input.append(new Option(o, o, false, selected.has(o)));
            input.style.fontSize = `${Math.max(9, Math.min(box.height * 0.6, 15))}px`;
          }
          input.disabled = readOnly;
          Object.assign(input.style, { left: `${box.left}px`, top: `${box.top}px`, width: `${box.width}px`, height: `${box.height}px` });
          page.el.append(input);
          c.inputs.push(input);
        });
        if (c.inputs.length) controls.push(c);
      }
      return controls;
    }

    async function save() {
      go.disabled = true;
      status.set("Saving…");
      try {
        const doc = await openPdfLib(state.bytes);
        const form = doc.getForm();
        const { font, clean } = await embedUnicodeFont(doc);
        for (const c of state.controls) {
          const f = form.getField(c.field.getName());
          if (f.isReadOnly()) continue;
          const [first] = c.inputs;
          if (c.type === "text") {
            const v = clean(first.value);
            f.setText(v || undefined);
          } else if (c.type === "check") {
            c.inputs.some((i) => i.checked) ? f.check() : f.uncheck();
          } else if (c.type === "radio") {
            const on = c.inputs.find((i) => i.checked);
            on ? f.select(on.value) : f.clear();
          } else if (c.type === "select") {
            first.value ? f.select(first.value) : f.clear();
          } else {
            const vals = [...first.selectedOptions].map((o) => o.value);
            vals.length ? f.select(vals) : f.clear();
          }
          if (c.type !== "check" && c.type !== "radio") fixAutoFontSize(f, c.type === "text" && f.isMultiline());
        }
        form.updateFieldAppearances(font);
        if (flatten.checked) form.flatten();
        const bytes = await doc.save({ useObjectStreams: true, updateFieldAppearances: false });
        const name = `${stem(state.name)}-filled.pdf`;
        downloadBlob(pdfBlob(bytes), name);
        status.set(`Done · downloaded ${name}`, "ok");
      } catch (e) {
        status.fail(e);
      }
      go.disabled = false;
    }

    return { addFiles };
  },
};
